### ISSUE TITLE
Add documentation and tests for the `LLMGenerateNode`

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#1279]
As part of Sherlock, a prototype of the `LLMGenerateNode` was created. This class will need the following improvements before being merged back to `branch-23.11`:

```[tasklist]
### Tasks
- [x] Add docstrings for the class (including when it should be used and what task it performs)
- [x] Add docstrings to each public method
- [x] Add unit tests for all public functions which execute all code paths
- [x] Add an integration test to verify the component works as part of a pipeline
```

You can find the prototype located [here](https://github.com/nv-morpheus/Morpheus/blob/de35ac300e7061bcfd3599c2c7f9b3373e71d703/examples/llm/common/llm_generate_node.py)

Note: the location above links directly to a commit with the prototype. The current location and functionality of the class may have changed.
