### ISSUE TITLE
Add documentation and tests for the `RetrieverNode`

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#1301]
As part of Sherlock, a prototype of the `RetrieverNode` was created. This class will need the following improvements before being merged back to `branch-23.11`:

```[tasklist]
### Tasks
- [ ] Add docstrings for the class (including when it should be used and what task it performs)
- [ ] Add docstrings to each public method
- [ ] Add unit tests for all public functions which execute all code paths 
- [ ] Add an integration test to verify the component works as part of a pipeline
```

You can find the prototype located [here](https://github.com/nv-morpheus/Morpheus/blob/a8c656d7a7912afe495d1852074d7c57aa434bc8/morpheus/llm/nodes/retriever_node.py)

Note: the location above links directly to a commit with the prototype. The current location and functionality of the class may have changed.
