### ISSUE TITLE
Remove Starter DFP

### ISSUE THREAD

**Issue by efajardo-nv** [nv-morpheus/Morpheus#1715]
### Is this a new feature, an improvement, or a change to existing functionality?

Change

### How would you describe the priority of this feature request

Medium

### Please provide a clear description of problem this feature solves

Instead of having two separate implementations of Digital Fingerprinting (DFP), [Starter DFP](https://github.com/nv-morpheus/Morpheus/tree/branch-24.06/examples/digital_fingerprinting/starter) will be removed in favor of [Production DFP](https://github.com/nv-morpheus/Morpheus/tree/branch-24.06/examples/digital_fingerprinting/production) which already incorporates new Morpheus features and can scale to production-ready deployments.

### Sub Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/nv-morpheus/Morpheus/issues/1641
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open feature requests](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request

**Comment by mdemoret-nv** [comment]
Additional things that need to be done with this issue:

- [ ] Remove all references to the Starter DFP in docs
- [ ] Remove classes which only exist for the starter DFP.
- [ ] Remove tests associated with the starter DFP

**Comment by dagardner-nv** [comment]
Relates to issue #1641
