### ISSUE TITLE
[EPIC] CPU Only Execution Mode

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#1846]
Tracking issue for the CPU only execution mode effort
```[tasklist]
### Tasks
- [ ] https://github.com/nv-morpheus/Morpheus/issues/562
- [x] Add API for getting/setting execution mode
- [x] Update sources and sinks to support CPU/GPU modes
- [x] Add suite of tests to ensure correct execution mode is being run
```
