### ISSUE TITLE
[DOC]: CLX/Morpheus Parity Comparison - Engineering

### ISSUE THREAD

**Issue by BartleyR** [nv-morpheus/Morpheus#508]
### How would you describe the priority of this documentation request

Medium

### Describe the future/missing documentation

The current RAPIDS CLX library has functionality that could be integrated into Morpheus. As the first step towards this, we wish to understand the parity between CLX and Morpheus in terms of the APIs, capabilities, developer tools, and methods that exist in both.

### Where have you looked?

No such documentation exist in CLX or Morpheus

### Tasks
Generated from @efajardo-nv's comment below

```[tasklist]
- [x] clx.analytics.loda.Loda
- [x] clx.analytics.multiclass_sequence_classifier.MulticlassSequenceClassifier
- [x] clx.parsers.splunk_notable_parser.SplunkNotableParser
- [x] clx.parsers.windows_event_parser.WindowsEventParser
- [x] clx.parsers.zeek.parse_log_file
- [x] clx.analytics.dga_detector.DGADetector
- [x] clx.dns.dns_extractor
- [x] clx.ip
```
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by efajardo-nv** [comment]
Possible CLX functionality to migrate:

LODA anomaly detection
- `clx.analytics.loda.Loda`
- Used in [Network Intrusion Detection in Netflow](https://github.com/rapidsai/clx/blob/branch-23.02/notebooks/ids_detection/IDS_using_LODA.ipynb)

Multi-class Sequence classifier
- `clx.analytics.multiclass_sequence_classifier.MulticlassSequenceClassifier`
- Can be used for various classifier use cases such as [Root Cause Analysis](https://github.com/nv-morpheus/Morpheus/tree/branch-23.01/examples/root_cause_analysis) which currently uses binary sequence classifier.

Splunk Notable Parser
- `clx.parsers.splunk_notable_parser.SplunkNotableParser`
- Used in [Analysis of Alert Notables from Splunk](https://github.com/rapidsai/clx/blob/branch-23.02/notebooks/alert_analysis/Alert_Analysis_with_CLX.ipynb)

Windows Event Log Parser
- `clx.parsers.windows_event_parser.WindowsEventParser`

Zeek Parser
- `clx.parsers.zeek.parse_log_file`
- Used in [CLX Supervised Asset Classification](https://github.com/rapidsai/clx/blob/branch-23.02/notebooks/network_mapping/CLX_Supervised_Asset_Classification.ipynb)

Domain Generation Algorithm (DGA) Detection
- `clx.analytics.dga_detector.DGADetector`
- Used in [CLX DGA Detection](https://github.com/rapidsai/clx/blob/branch-23.02/notebooks/dga_detection/DGA_Detection.ipynb)

DNS Extractor
- `clx.dns.dns_extractor`

**Comment by efajardo-nv** [comment]
CLX LODA migrated via https://github.com/nv-morpheus/morpheus-experimental/pull/38

**Comment by efajardo-nv** [comment]
all tasks completed/merged.
