### ISSUE TITLE
[FEA] Improve Devcontainer Tracking Issue

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#701]
This issue is tracking all of the various updates to the Morpheus DevContainer that are planned out. These will be completed in stages as outlined by the top level issues.

```[tasklist]
### Tasks
- [ ] Replicate current devcontainer functionality using features
- [ ] Setup the docker user to match the host user
- [ ] Install Mamba with the correct user permissions
- [ ] Including setting the default conda environment
- [ ] The default conda environment should be activated as part of the image or entry point to allow VS Code to use conda installed packages
- [ ] Setup docker-in-docker
- [ ] Add the Github CLI
- [ ] Including mounting the host configuration into the container where possible
```

**Comment by mdemoret-nv** [comment]
Moving the tracking issue to 23.07.

**Comment by mdemoret-nv** [comment]
Moving tracking issue to next release
